version: "3.2"
services:
  weston:
    image: torizon/arm32v7-debian-weston:latest
    privileged: true
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp

  codesys:
    image: torizonextras/codesys
    privileged: true
    network_mode: host

  kiosk:
    image: torizon/arm32v7-debian-kiosk-mode-browser:latest
    command: http://localhost:8080
    privileged: true
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
    depends_on:
      - codesys
      - weston